export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
] as const;

export function findClosestCountries(query: string, limit = 5): string[] {
  const trimmed = query.trim().toLowerCase();

  if (!trimmed) {
    return [];
  }

  return COUNTRIES.filter((country) => country.toLowerCase().includes(trimmed))
    .sort((a, b) => {
      const aIndex = a.toLowerCase().indexOf(trimmed);
      const bIndex = b.toLowerCase().indexOf(trimmed);
      if (aIndex !== bIndex) {
        return aIndex - bIndex;
      }
      return a.localeCompare(b);
    })
    .slice(0, limit);
}

export function isValidCountry(value: string): boolean {
  return (COUNTRIES as readonly string[]).includes(value.trim());
}

// ISO 3166-1 numeric codes, matching the ids used by world-atlas topojson features.
export const COUNTRY_ISO_NUMERIC: Record<string, string> = {
  Afghanistan: "004",
  Albania: "008",
  Algeria: "012",
  Andorra: "020",
  Angola: "024",
  "Antigua and Barbuda": "028",
  Argentina: "032",
  Armenia: "051",
  Australia: "036",
  Austria: "040",
  Azerbaijan: "031",
  Bahamas: "044",
  Bahrain: "048",
  Bangladesh: "050",
  Barbados: "052",
  Belarus: "112",
  Belgium: "056",
  Belize: "084",
  Benin: "204",
  Bhutan: "064",
  Bolivia: "068",
  "Bosnia and Herzegovina": "070",
  Botswana: "072",
  Brazil: "076",
  Brunei: "096",
  Bulgaria: "100",
  "Burkina Faso": "854",
  Burundi: "108",
  "Cabo Verde": "132",
  Cambodia: "116",
  Cameroon: "120",
  Canada: "124",
  "Central African Republic": "140",
  Chad: "148",
  Chile: "152",
  China: "156",
  Colombia: "170",
  Comoros: "174",
  Congo: "178",
  "Costa Rica": "188",
  Croatia: "191",
  Cuba: "192",
  Cyprus: "196",
  Czechia: "203",
  "Democratic Republic of the Congo": "180",
  Denmark: "208",
  Djibouti: "262",
  Dominica: "212",
  "Dominican Republic": "214",
  Ecuador: "218",
  Egypt: "818",
  "El Salvador": "222",
  "Equatorial Guinea": "226",
  Eritrea: "232",
  Estonia: "233",
  Eswatini: "748",
  Ethiopia: "231",
  Fiji: "242",
  Finland: "246",
  France: "250",
  Gabon: "266",
  Gambia: "270",
  Georgia: "268",
  Germany: "276",
  Ghana: "288",
  Greece: "300",
  Grenada: "308",
  Guatemala: "320",
  Guinea: "324",
  "Guinea-Bissau": "624",
  Guyana: "328",
  Haiti: "332",
  Honduras: "340",
  Hungary: "348",
  Iceland: "352",
  India: "356",
  Indonesia: "360",
  Iran: "364",
  Iraq: "368",
  Ireland: "372",
  Israel: "376",
  Italy: "380",
  "Ivory Coast": "384",
  Jamaica: "388",
  Japan: "392",
  Jordan: "400",
  Kazakhstan: "398",
  Kenya: "404",
  Kiribati: "296",
  Kuwait: "414",
  Kyrgyzstan: "417",
  Laos: "418",
  Latvia: "428",
  Lebanon: "422",
  Lesotho: "426",
  Liberia: "430",
  Libya: "434",
  Liechtenstein: "438",
  Lithuania: "440",
  Luxembourg: "442",
  Madagascar: "450",
  Malawi: "454",
  Malaysia: "458",
  Maldives: "462",
  Mali: "466",
  Malta: "470",
  "Marshall Islands": "584",
  Mauritania: "478",
  Mauritius: "480",
  Mexico: "484",
  Micronesia: "583",
  Moldova: "498",
  Monaco: "492",
  Mongolia: "496",
  Montenegro: "499",
  Morocco: "504",
  Mozambique: "508",
  Myanmar: "104",
  Namibia: "516",
  Nauru: "520",
  Nepal: "524",
  Netherlands: "528",
  "New Zealand": "554",
  Nicaragua: "558",
  Niger: "562",
  Nigeria: "566",
  "North Korea": "408",
  "North Macedonia": "807",
  Norway: "578",
  Oman: "512",
  Pakistan: "586",
  Palau: "585",
  Palestine: "275",
  Panama: "591",
  "Papua New Guinea": "598",
  Paraguay: "600",
  Peru: "604",
  Philippines: "608",
  Poland: "616",
  Portugal: "620",
  Qatar: "634",
  Romania: "642",
  Russia: "643",
  Rwanda: "646",
  "Saint Kitts and Nevis": "659",
  "Saint Lucia": "662",
  "Saint Vincent and the Grenadines": "670",
  Samoa: "882",
  "San Marino": "674",
  "Sao Tome and Principe": "678",
  "Saudi Arabia": "682",
  Senegal: "686",
  Serbia: "688",
  Seychelles: "690",
  "Sierra Leone": "694",
  Singapore: "702",
  Slovakia: "703",
  Slovenia: "705",
  "Solomon Islands": "090",
  Somalia: "706",
  "South Africa": "710",
  "South Korea": "410",
  "South Sudan": "728",
  Spain: "724",
  "Sri Lanka": "144",
  Sudan: "729",
  Suriname: "740",
  Sweden: "752",
  Switzerland: "756",
  Syria: "760",
  Taiwan: "158",
  Tajikistan: "762",
  Tanzania: "834",
  Thailand: "764",
  "Timor-Leste": "626",
  Togo: "768",
  Tonga: "776",
  "Trinidad and Tobago": "780",
  Tunisia: "788",
  Turkey: "792",
  Turkmenistan: "795",
  Tuvalu: "798",
  Uganda: "800",
  Ukraine: "804",
  "United Arab Emirates": "784",
  "United Kingdom": "826",
  "United States": "840",
  Uruguay: "858",
  Uzbekistan: "860",
  Vanuatu: "548",
  "Vatican City": "336",
  Venezuela: "862",
  Vietnam: "704",
  Yemen: "887",
  Zambia: "894",
  Zimbabwe: "716",
};

const ISO_TO_COUNTRY: Record<string, string> = Object.fromEntries(
  Object.entries(COUNTRY_ISO_NUMERIC).map(([country, iso]) => [iso, country])
);

export function isoForCountry(country: string): string | null {
  return COUNTRY_ISO_NUMERIC[country.trim()] ?? null;
}

export function countryForIso(iso: string): string | null {
  return ISO_TO_COUNTRY[iso] ?? null;
}
