export const STUDIES = [
  "Accountancy and Controlling",
  "Advanced European Union Law",
  "American Studies",
  "Ancient History",
  "Anthropology of Religion and Culture",
  "Applied Cognitive Neuroscience",
  "Applied Linguistics and Multilingualism",
  "Applied Mathematics",
  "Applied Physics",
  "Archaeology",
  "Art History",
  "Artificial Intelligence",
  "Arts & Culture",
  "Arts and Culture",
  "Arts Culture and Media",
  "Arts in Society",
  "Arts Media and Literary Studies",
  "Astronomy",
  "Behavioural and Cognitive Neurosciences",
  "Behavioural and Social Sciences",
  "Bioinformatics for the Life Sciences",
  "Biology",
  "Biomedical Engineering",
  "Biomedical Sciences",
  "Biomolecular Sciences",
  "Biotechnology",
  "Business Administration",
  "Business Administration: Health",
  "Chemical Engineering",
  "Chemistry",
  "Classical Medieval and Early Modern Studies",
  "Classics",
  "Classics & Ancient Civilizations",
  "Clinical Forensic Psychology & Victimology",
  "Clinical Neuropsychology",
  "Communication and Information Studies",
  "Computational Cognitive Science",
  "Computing Science",
  "Creative Media & Game Technologies",
  "Creative Media and Game Technologies",
  "Cultural Leadership",
  "Curatorial Studies",
  "Data Science & Society",
  "Data Science for Life Sciences",
  "DDM Demography and Social Inequality",
  "DDM Development Planning and Infrastructure Management",
  "DDM Economic Development and Growth (MEDEG)",
  "DDM Finance",
  "DDM Financial Management",
  "DDM International Development Economics",
  "DDM Marketing & Finance",
  "DDM Marketing & Information Systems",
  "DDM Social Demography",
  "DDM Strategic Marketing Intelligence",
  "DDM Sustainable Marine and Coastal Management",
  "DDM Sustainable Water Management",
  "DDM Urban Governance within a Global Environment",
  "DDM Urban Planning Environment and Infrastructure",
  "Deafblindness",
  "Digital Humanities",
  "East Asian Studies",
  "Ecology and Evolution",
  "Econometrics and Operations Research",
  "Econometrics Operations Research and Actuarial Studies",
  "Economic Geography",
  "Economic Geography: Regional Competitiveness and Trade",
  "Economics",
  "Economics and Business Economics",
  "Electrical and Electronic Engineering",
  "Energy & Power Electronics",
  "Energy and Climate Law",
  "Energy and Environmental Sciences",
  "Energy for Society",
  "Energy Governance",
  "English Language and Culture",
  "English Literature and Culture",
  "Environmental and Infrastructure Planning",
  "Environmental Psychology",
  "European Master in Renewable Energy",
  "European Master in Sustainable Energy System Management",
  "European Politics in a Global Perspective",
  "Film and Contemporary Audiovisual Media",
  "Finance",
  "Fine Art",
  "Geopolitics & Connectivity",
  "Global Criminal Law",
  "Global Politics & Sustainability",
  "Heritage and Religion",
  "History",
  "History of Architecture and Urbanism",
  "Human Geography and Planning",
  "Human Resource Management",
  "Industrial Engineering and Management",
  "Information Science",
  "Interdisciplinary Business Professional",
  "Interdisciplinary Research in Health Dynamics",
  "International and European Law",
  "International Business",
  "International Business 3-year programme",
  "International Business and Management",
  "International Commercial Law",
  "International Communication",
  "International Economics and Sustainable Development",
  "International Facility Management",
  "International Finance & Control",
  "International Humanitarian Action (120 EC)",
  "International Law & Relations",
  "International Political Economy",
  "International Relations",
  "International Relations (120 EC)",
  "International Relations (60 EC)",
  "International Relations and International Organization",
  "International Security",
  "Islands and Sustainability (EM)",
  "Journalism (English taught)",
  "Klinische Psychologie",
  "Language and Cognition",
  "Learning in Interaction",
  "Liberal Arts and Sciences",
  "Life Science and Technology",
  "Linguistics",
  "Literary Studies",
  "Marine Biology",
  "Marketing",
  "Marketing Management",
  "Master in International Business and Management",
  "Master International Communication",
  "Master Legal Research",
  "Mathematics",
  "Mechanical Engineering",
  "Mechatronics",
  "Media Cultural Industries and Innovation",
  "Media Digital Transformations and Society",
  "Media Studies",
  "Medical Biology",
  "Medical Pharmaceutical Sciences",
  "Middle Eastern Studies",
  "Modern History and International Relations",
  "Molecular & Cell Biology",
  "Molecular Medicine and Innovative Treatment",
  "MSc Marketing - Marketing Analytics and Data Science",
  "MSc Marketing - Marketing Management",
  "Multilingualism",
  "Nanoscience",
  "Natural Language Processing",
  "Philosophy",
  "Philosophy and Science",
  "Philosophy of a specific discipline",
  "Philosophy Politics and Economics",
  "Physics",
  "Physiotherapy",
  "Popular Music and Sonic Cultures",
  "Population Studies",
  "Psychology",
  "Psychology (EN)",
  "Public International Law",
  "Real Estate Studies",
  "Religion and Pluralism Ancient & Modern",
  "Religion Conflict and Globalization",
  "Religious Diversity in a Globalised World (EM)",
  "Religious Studies",
  "Renewable Energy Materials and Processing",
  "Research Master in Economics and Business",
  "Science Education and Communication",
  "Sensors & Smart Systems",
  "Smart Systems Engineering",
  "Society Sustainability and Planning",
  "Spatial Planning and Design",
  "Spatial Sciences",
  "Supply Chain Management",
  "Sustainable Entrepreneurship",
  "Talent Development and Creativity",
  "Technology and Operations Management",
  "Technology Law and Innovation",
  "Theology & Religious Studies",
  "Theoretical and Empirical Linguistics",
  "Theory and History of Psychology",
  "Work Organizational and Personnel Psychology",
  "Writing Editing and Mediating",
] as const;

export function findClosestStudies(query: string, limit = 5): string[] {
  const trimmed = query.trim().toLowerCase();

  if (!trimmed) {
    return [];
  }

  return STUDIES.filter((study) => study.toLowerCase().includes(trimmed))
    .sort((a, b) => {
      const aIndex = a.toLowerCase().indexOf(trimmed);
      const bIndex = b.toLowerCase().indexOf(trimmed);
      if (aIndex !== bIndex) {
        return aIndex - bIndex;
      }
      return a.localeCompare(b);
    })
    .slice(0, limit);
}

export function isValidStudy(value: string): boolean {
  return (STUDIES as readonly string[]).includes(value.trim());
}
